Release adaptive
harshitkathuria/InternDigger pull request #4
Opened 2021-01-21 16:38 UTC by Kirill-frontend

2021-01-21 20:27 UTC, harshitkathuria requested changes
![image](https://user-images.githubusercontent.com/67231570/105407599-f1944880-5c53-11eb-9ce9-cc87e3f90775.png)

The signup section and signup form page going out of viewport. Try to check responsiveness on standard devices.

**Please see comments and update accordingly**

2021-01-21 20:27 UTC, harshitkathuria commented on public/css/main.css
> +  -ms-grid-columns: (1fr)[4];
Please refrain from using [4], instead replace it with repeat().

2021-01-22 01:55 UTC, Kirill-frontend commented
I have not touched the grid's, and I do not quite understand where it goes off the screen

2021-01-22 07:35 UTC, harshitkathuria commented
> I have not touched the grid's, and I do not quite understand where it goes off the screen

The signup section on the landing page has two parts. One for recruiter and another one for students. The students section's signup button is overflowing. And the same goes for signup form.

2021-01-22 07:52 UTC, harshitkathuria commented
> I have not touched the grid's, and I do not quite understand where it goes off the screen

Sorry, It was my mistake. Just comment out or replace the [4] with repeat(4, 1fr) and then it will be ready to merged. :)

2021-01-22 16:38 UTC, harshitkathuria commented
LGTM, Thanks

2021-01-22 16:39 UTC, merged

2021-01-22 17:35 UTC, Kirill-frontend commented
Ok I was glad to help